#define HTS_CC "gcc -std=gnu11"
#define HTS_CPPFLAGS "-I/cluster/home/Kangwen/opt/bzip2/include"
#define HTS_CFLAGS "-g -O2 -fvisibility=hidden"
#define HTS_LDFLAGS "-L/cluster/home/Kangwen/opt/bzip2/lib -Wl,-R/cluster/home/Kangwen/opt/bzip2/lib -fvisibility=hidden "
#define HTS_LIBS "-lz -lm  "
